services:
  accounts:
    image: "dundiramesh/accounts:v1"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 300M
    networks:
      - dundiramesh
  loans:
    image: "dundiramesh/loans:v1"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 300M
    networks:
      - dundiramesh
  cards:
    image: "dundiramesh/cards:v1"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 300M
    networks:
      - dundiramesh
networks:
  dundiramesh:
    driver: "bridge"